### ISSUE TITLE
Mod loading crash

### ISSUE THREAD

**Issue by Sereath** [fullskele/FlaskOfLife-Mod-1.12.2#2]
After updating to 1.0.3, I promptly got this.

Two crashes at the same time for some reason:

https://gist.github.com/Sereath/60814cc5d1c96c701d47d831ab597972
https://gist.github.com/Sereath/f5ffe4a268685198de20d736c8bd310a

**Comment by fullskele** [comment]
Should be fixed in v1.0.3HOTFIX. Thank you very much for the reports!

**Comment by Sereath** [comment]
Thanks for the fixes too!
