### ISSUE TITLE
Not working on servers

### ISSUE THREAD

**Issue by Sereath** [fullskele/FlaskOfLife-Mod-1.12.2#3]
No crashes this time, it just does nothing on a server.

![image](https://github.com/user-attachments/assets/57274baa-2628-4bfd-92be-9bc9106ae4ff)

latest.log:
https://gist.github.com/Sereath/674fe173ba2233df3cfe9a7f50fe578e

**Comment by fullskele** [comment]
Meaning no item was registered on the server?

**Comment by Sereath** [comment]
The item does exist but attempting to drink from it does nothing, it just spams the log.

**Comment by fullskele** [comment]
Should be fixed in v1.0.3HOTFIX-2

**Comment by Sereath** [comment]
Same issue, unfortunately.
Here is a clip:
https://youtu.be/2Ziji1y0An4

latest.log:
https://gist.github.com/Sereath/70b627bac33f0ad3f9451b5a1123b6bb

debug.log:
https://gist.github.com/Sereath/45d4d56b75c2b385a301b158670a54d0

**Comment by fullskele** [comment]
I'm terribly sorry, should finally be fixed in v1.0.3HOTFIX-3.

**Comment by Sereath** [comment]
No problem and thank you. It works now. ✅

![image](https://github.com/user-attachments/assets/e03ad21d-d7a2-4aaa-bdbb-9c2d5117666e)
